spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: WARN
    com.financeapp: INFO
    org.springframework.security: WARN
